services:
- type: pserv
  name: mysql-5
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql-5
    mountPath: /var/lib/mysql
    sizeGB: 5
  envVars:
  - fromGroup: mysql-5

envVarGroups:
- name: mysql-5
  envVars:
  - key: DB_NAME
    value: mysql-5
  - key: DB_USER
    value: mysql-5
  - key: DB_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true